version: '3.9'

services:
  versionist:
    build:
      context: ./
      dockerfile: Dockerfile
      ssh:
        - default
    image: diogoandrade/versionist:latest
# uncomment this if you want to use your local github ssh keys
# inside the container
    # secrets:
    #   - github-ssh-key
    container_name: versionist
    volumes:
      - ${PWD}:/app
    tty: true
    entrypoint: ['/bin/bash']
# uncomment this if you want to use your local github ssh keys
# inside the container
# secrets:
#   github-ssh-key:
#     file: ${HOME}/.ssh/id_ed25519
# testing my sig key
